/**
 * Générateur de script SQLite.
 *
 * SQLite ne permet pas d'ajouter une clé étrangère après coup avec
 * `ALTER TABLE ... ADD CONSTRAINT` : le mode `inline` est donc imposé,
 * indépendamment de l'option `foreignKeyMode` reçue (le moteur partagé
 * retombe automatiquement sur le premier mode listé dans
 * `allowedForeignKeyModes` lorsque le mode demandé n'est pas supporté).
 *
 * Le script commence toujours par `PRAGMA foreign_keys = ON;`, activant la
 * vérification des clés étrangères (désactivée par défaut par SQLite). Les
 * `DROP TABLE`, quand ils sont activés, sont encadrés par un cycle
 * OFF/ON supplémentaire pour autoriser une suppression dans un ordre
 * quelconque (utile en présence de cycles ou d'associations réflexives).
 *
 * Aucune limite de longueur de nom de contrainte n'est imposée par SQLite en
 * pratique ; une limite large (1024 octets) garde néanmoins le mécanisme de
 * troncature générique fonctionnel et testable.
 */
import type { SqlGenerationOptions, SqlGenerationResult } from '../dialect';
import { DEFAULT_SQL_GENERATION_OPTIONS } from '../dialect';
import type { DialectSyntax } from '../shared/generate-script';
import { generateSqlScript } from '../shared/generate-script';
import { mapSqliteDataType } from './data-types';
import { quoteSqliteIdentifier } from './identifier';

const SQLITE_MAX_CONSTRAINT_NAME_BYTES = 1024;

const SQLITE_SYNTAX: DialectSyntax = {
  id: 'sqlite',
  header: '-- Generated by Modrise\n-- SQLite dialect',
  quoteIdentifier: quoteSqliteIdentifier,
  mapDataType: mapSqliteDataType,
  maxConstraintNameBytes: SQLITE_MAX_CONSTRAINT_NAME_BYTES,
  allowedForeignKeyModes: ['inline'],
  dropStatementSuffix: '',
  dropWrapper: {
    before: 'PRAGMA foreign_keys = OFF;',
    after: 'PRAGMA foreign_keys = ON;',
  },
  preamble: 'PRAGMA foreign_keys = ON;',
};

export function generateSqliteScript(
  model: Parameters<typeof generateSqlScript>[0],
  options: SqlGenerationOptions = DEFAULT_SQL_GENERATION_OPTIONS,
): SqlGenerationResult {
  return generateSqlScript(model, options, SQLITE_SYNTAX);
}
