import { afterEach, describe, expect, it, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { createHotelExampleProject } from '@/core/examples/hotel';
import { createEntity } from '@/core/conceptual-model/factories';
import { createProject } from '@/core/project/types';
import { useProjectStore } from '@/stores/project-store';
import { useUiStore } from '@/stores/ui-store';
import { TooltipProvider } from '@/components/ui/tooltip';
import { SqlPreviewPanel } from './SqlPreviewPanel';

function loadProject(project: ReturnType<typeof createProject>) {
  useProjectStore.getState().loadProject(project);
}

function renderPanel() {
  return render(
    <TooltipProvider>
      <SqlPreviewPanel />
    </TooltipProvider>,
  );
}

function mockClipboard(writeText: (text: string) => Promise<void>) {
  Object.defineProperty(navigator, 'clipboard', {
    value: { writeText },
    configurable: true,
  });
}

afterEach(() => {
  vi.restoreAllMocks();
});

describe('SqlPreviewPanel', () => {
  it('affiche le SQL généré pour le projet exemple', () => {
    loadProject(createHotelExampleProject());
    renderPanel();
    const code = screen.getByTestId('sql-code');
    expect(code).toHaveTextContent('CREATE TABLE "client"');
    expect(code).toHaveTextContent('CREATE TABLE "reservation"');
    expect(code).toHaveTextContent('FOREIGN KEY');
  });

  it('affiche un état bloqué quand le MCD contient des erreurs', () => {
    const project = createProject();
    project.conceptualModel.entities.push(createEntity({ name: '' }));
    loadProject(project);
    renderPanel();
    expect(screen.getByTestId('sql-preview-blocked')).toBeInTheDocument();
    expect(screen.queryByTestId('sql-preview-panel')).not.toBeInTheDocument();
  });

  it('le bouton du message bloquant bascule vers l’onglet validation', async () => {
    const project = createProject();
    project.conceptualModel.entities.push(createEntity({ name: '' }));
    loadProject(project);
    useUiStore.getState().setBottomTab('sql');
    renderPanel();
    screen.getByRole('button', { name: 'Ouvrir la validation' }).click();
    expect(useUiStore.getState().bottomTab).toBe('validation');
  });

  it('le bouton copier est désactivé sans SQL et activé avec un SQL valide', () => {
    loadProject(createHotelExampleProject());
    renderPanel();
    expect(screen.getByTestId('sql-copy-button')).toBeEnabled();
    expect(screen.getByTestId('sql-download-button')).toBeEnabled();
  });

  it('copie le SQL dans le presse-papiers et affiche une confirmation', async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    loadProject(createHotelExampleProject());
    const user = userEvent.setup();
    renderPanel();
    mockClipboard(writeText);
    await user.click(screen.getByTestId('sql-copy-button'));
    expect(writeText).toHaveBeenCalledWith(expect.stringContaining('CREATE TABLE "client"'));
    await vi.waitFor(() => {
      expect(useUiStore.getState().notifications.map((n) => n.message)).toContain('SQL copié');
    });
  });

  it('affiche un message d’erreur si la copie échoue', async () => {
    const writeText = vi.fn().mockRejectedValue(new Error('denied'));
    loadProject(createHotelExampleProject());
    const user = userEvent.setup();
    renderPanel();
    mockClipboard(writeText);
    await user.click(screen.getByTestId('sql-copy-button'));
    await vi.waitFor(() => {
      expect(useUiStore.getState().notifications.map((n) => n.message)).toContain(
        'Impossible de copier le SQL',
      );
    });
  });

  it("l'option En-tête modifie le SQL affiché", async () => {
    loadProject(createHotelExampleProject());
    const user = userEvent.setup();
    renderPanel();
    expect(screen.getByTestId('sql-code')).toHaveTextContent('Generated by Modrise');
    await user.click(screen.getByText('En-tête'));
    expect(screen.getByTestId('sql-code')).not.toHaveTextContent('Generated by Modrise');
  });

  it("l'option DROP TABLE ajoute les instructions correspondantes", async () => {
    loadProject(createHotelExampleProject());
    const user = userEvent.setup();
    renderPanel();
    expect(screen.getByTestId('sql-code')).not.toHaveTextContent('DROP TABLE');
    await user.click(screen.getByText('DROP TABLE'));
    expect(screen.getByTestId('sql-code')).toHaveTextContent('DROP TABLE IF EXISTS');
  });

  it('se met à jour après une modification du MCD', () => {
    loadProject(createProject());
    const entity = useProjectStore.getState().addEntity();
    useProjectStore.getState().updateEntity(entity.id, { name: 'PRODUIT' });
    const { rerender } = renderPanel();
    expect(screen.getByTestId('sql-code')).toHaveTextContent('CREATE TABLE "produit"');

    useProjectStore.getState().updateEntity(entity.id, { name: 'ARTICLE' });
    rerender(
      <TooltipProvider>
        <SqlPreviewPanel />
      </TooltipProvider>,
    );
    expect(screen.getByTestId('sql-code')).toHaveTextContent('CREATE TABLE "article"');
  });
});
