/**
 * Générateur de script MySQL / MariaDB.
 *
 * Fine couche au-dessus du moteur partagé : clés étrangères via `ALTER
 * TABLE` par défaut comme PostgreSQL (cohérence entre dialectes, gestion des
 * cycles et des associations réflexives), `DROP TABLE` encadré par
 * `SET FOREIGN_KEY_CHECKS = 0/1` uniquement quand il est activé, limite de
 * noms de contrainte à 64 caractères.
 *
 * Les commentaires SQL (`COMMENT` inline sur colonnes/table) nécessiteraient
 * une syntaxe entièrement différente de celle de PostgreSQL (`COMMENT ON`) —
 * hors périmètre de cette phase : si `includeComments` est demandé, le
 * moteur partagé émet une issue informative plutôt que d'improviser une
 * implémentation partielle.
 */
import type { SqlGenerationOptions, SqlGenerationResult } from '../dialect';
import { DEFAULT_SQL_GENERATION_OPTIONS } from '../dialect';
import type { DialectSyntax } from '../shared/generate-script';
import { generateSqlScript } from '../shared/generate-script';
import { mapMySqlDataType } from './data-types';
import { quoteMySqlIdentifier } from './identifier';

const MYSQL_SYNTAX: DialectSyntax = {
  id: 'mysql',
  header: '-- Generated by Modrise\n-- MySQL / MariaDB dialect',
  quoteIdentifier: quoteMySqlIdentifier,
  mapDataType: mapMySqlDataType,
  maxConstraintNameBytes: 64,
  allowedForeignKeyModes: ['alter-table', 'inline'],
  dropStatementSuffix: '',
  dropWrapper: {
    before: 'SET FOREIGN_KEY_CHECKS = 0;',
    after: 'SET FOREIGN_KEY_CHECKS = 1;',
  },
};

export function generateMySqlScript(
  model: Parameters<typeof generateSqlScript>[0],
  options: SqlGenerationOptions = DEFAULT_SQL_GENERATION_OPTIONS,
): SqlGenerationResult {
  return generateSqlScript(model, options, MYSQL_SYNTAX);
}
