/**
 * Générateur de script PostgreSQL à partir d'un `LogicalModel`.
 *
 * Pur, déterministe, sans état partagé entre deux appels : un registre de
 * noms de contraintes frais est créé à chaque génération. Aucun UUID ni
 * horodatage n'entre dans la sortie.
 *
 * Ordre du script : en-tête optionnel, `DROP TABLE` optionnels, `CREATE
 * TABLE` (un par table, dans l'ordre du MLD), `ALTER TABLE ... ADD
 * CONSTRAINT` pour les clés étrangères (mode par défaut), puis `COMMENT ON`
 * optionnels. Une ligne vide sépare chaque bloc ; le fichier se termine par
 * un seul retour à la ligne.
 */
import type { LogicalModel, LogicalTable } from '../../logical-model/types';
import type {
  KeywordCase,
  SqlGenerationIssue,
  SqlGenerationOptions,
  SqlGenerationResult,
} from '../dialect';
import { DEFAULT_SQL_GENERATION_OPTIONS } from '../dialect';
import { mapPostgreSqlDataType } from './data-types';
import { quotePostgreSqlIdentifier } from './identifier';
import { SqlConstraintNameRegistry } from './constraint-registry';
import { validateLogicalModelForSql } from './validate-logical-model';

export const SQL_GENERATION_CODES = {
  constraintNameCollisionResolved: 'SQL_CONSTRAINT_NAME_COLLISION_RESOLVED',
  constraintNameTruncated: 'SQL_CONSTRAINT_NAME_TRUNCATED',
  internalGenerationError: 'INTERNAL_SQL_GENERATION_ERROR',
} as const;

interface TableConstraintNames {
  primaryKey?: string;
  uniqueConstraints: Map<string, string>;
  foreignKeys: Map<string, string>;
}

export function generatePostgreSqlScript(
  model: LogicalModel,
  options: SqlGenerationOptions = DEFAULT_SQL_GENERATION_OPTIONS,
): SqlGenerationResult {
  try {
    const validationIssues = validateLogicalModelForSql(model);
    if (validationIssues.some((issue) => issue.severity === 'error')) {
      return { success: false, sql: '', issues: validationIssues };
    }

    const issues: SqlGenerationIssue[] = [];
    const pushIssue = (issue: Omit<SqlGenerationIssue, 'id'>): void => {
      issues.push({ id: `sql-issue-${issues.length + 1}`, ...issue });
    };

    const tableById = new Map(model.tables.map((table) => [table.id, table]));
    const registry = new SqlConstraintNameRegistry();
    const constraintNames = computeConstraintNames(model, tableById, registry, pushIssue);

    const blocks: string[] = [];

    if (options.includeHeader) {
      blocks.push('-- Generated by Modrise\n-- PostgreSQL dialect');
    }

    if (options.includeDropStatements) {
      const K = (word: string) => applyKeywordCase(word, options.keywordCase);
      const dropLines = [...model.tables]
        .reverse()
        .map(
          (table) =>
            `${K('DROP TABLE IF EXISTS')} ${quotePostgreSqlIdentifier(table.name)} ${K('CASCADE')}${terminator(options)}`,
        );
      blocks.push(dropLines.join('\n'));
    }

    for (const table of model.tables) {
      blocks.push(renderCreateTable(table, tableById, constraintNames.get(table.id)!, options));
    }

    if (options.foreignKeyMode === 'alter-table') {
      for (const table of model.tables) {
        for (const foreignKey of table.foreignKeys) {
          const referencedTable = tableById.get(foreignKey.referencedTableId);
          if (!referencedTable) continue; // écarté par la validation défensive sinon
          blocks.push(
            renderAlterTableForeignKey(
              table,
              foreignKey,
              referencedTable,
              constraintNames.get(table.id)!.foreignKeys.get(foreignKey.id)!,
              options,
            ),
          );
        }
      }
    }

    if (options.includeComments) {
      for (const table of model.tables) {
        const commentBlock = renderComments(table, options);
        if (commentBlock) blocks.push(commentBlock);
      }
    }

    const sql = `${blocks.join('\n\n')}\n`;
    return { success: true, sql, issues };
  } catch (error) {
    console.error('Erreur inattendue pendant la génération SQL PostgreSQL :', error);
    return {
      success: false,
      sql: '',
      issues: [
        {
          id: 'internal-error',
          severity: 'error',
          code: SQL_GENERATION_CODES.internalGenerationError,
          message:
            'Une erreur interne inattendue a empêché la génération du SQL. Consultez la console pour plus de détails.',
          sourceIds: [],
        },
      ],
    };
  }
}

function terminator(options: SqlGenerationOptions): string {
  return options.statementTerminator ? ';' : '';
}

function applyKeywordCase(word: string, keywordCase: KeywordCase): string {
  return keywordCase === 'lower' ? word.toLowerCase() : word.toUpperCase();
}

function columnName(table: LogicalTable, columnId: string): string {
  return table.columns.find((column) => column.id === columnId)?.name ?? columnId;
}

/**
 * Calcule les noms de contraintes SQL pour chaque table, dans un ordre
 * stable (clé primaire, puis contraintes uniques, puis clés étrangères).
 * Les noms de contraintes du MLD (`uniqueConstraint.name`, `foreignKey.name`)
 * ne sont pas réutilisés tels quels : la convention SQL (`pk_<table>`,
 * `uq_<table>_<colonnes>`, `fk_<table>_<table référencée>`) est calculée ici
 * pour rester la seule source de vérité du nommage des contraintes SQL.
 */
function computeConstraintNames(
  model: LogicalModel,
  tableById: ReadonlyMap<string, LogicalTable>,
  registry: SqlConstraintNameRegistry,
  pushIssue: (issue: Omit<SqlGenerationIssue, 'id'>) => void,
): Map<string, TableConstraintNames> {
  const result = new Map<string, TableConstraintNames>();

  const reserve = (baseName: string, sourceIds: string[]): string => {
    const { name, collided, truncated } = registry.reserve(baseName);
    if (collided) {
      pushIssue({
        severity: 'warning',
        code: SQL_GENERATION_CODES.constraintNameCollisionResolved,
        message: `Le nom de contrainte SQL généré à partir de « ${baseName} » entrait en collision ; « ${name} » a été utilisé à la place.`,
        sourceIds,
      });
    }
    if (truncated) {
      pushIssue({
        severity: 'info',
        code: SQL_GENERATION_CODES.constraintNameTruncated,
        message: `Le nom de contrainte SQL généré à partir de « ${baseName} » dépassait la limite de 63 octets de PostgreSQL et a été raccourci en « ${name} ».`,
        sourceIds,
      });
    }
    return name;
  };

  for (const table of model.tables) {
    const names: TableConstraintNames = {
      uniqueConstraints: new Map(),
      foreignKeys: new Map(),
    };

    if (table.primaryKey.length > 0) {
      names.primaryKey = reserve(`pk_${table.name}`, [table.id]);
    }

    for (const uniqueConstraint of table.uniqueConstraints) {
      const columnNames = uniqueConstraint.columnIds.map((id) => columnName(table, id));
      names.uniqueConstraints.set(
        uniqueConstraint.id,
        reserve(`uq_${table.name}_${columnNames.join('_')}`, [table.id, uniqueConstraint.id]),
      );
    }

    for (const foreignKey of table.foreignKeys) {
      const referencedTable = tableById.get(foreignKey.referencedTableId);
      const baseName = referencedTable
        ? foreignKeyBaseName(table, foreignKey, referencedTable)
        : `fk_${table.name}`;
      names.foreignKeys.set(foreignKey.id, reserve(baseName, [table.id, foreignKey.id]));
    }

    result.set(table.id, names);
  }

  return result;
}

/**
 * Nom de base d'une clé étrangère : `fk_<table>_<table référencée>`, sauf
 * lorsque plusieurs clés étrangères de la même table pointent vers la même
 * table référencée (association réflexive multiple) — un qualificatif est
 * alors dérivé du nom de la première colonne locale de la clé (déjà préfixée
 * par le rôle lors de la transformation MCD → MLD), ex. `fk_employe_manager`
 * / `fk_employe_subordonne` plutôt qu'un suffixe numérique peu lisible.
 */
function foreignKeyBaseName(
  table: LogicalTable,
  foreignKey: LogicalTable['foreignKeys'][number],
  referencedTable: LogicalTable,
): string {
  const sameTargetCount = table.foreignKeys.filter(
    (fk) => fk.referencedTableId === foreignKey.referencedTableId,
  ).length;
  if (sameTargetCount > 1) {
    const qualified = deriveQualifiedForeignKeyBaseName(table, foreignKey, referencedTable);
    if (qualified) return qualified;
  }
  return `fk_${table.name}_${referencedTable.name}`;
}

function deriveQualifiedForeignKeyBaseName(
  table: LogicalTable,
  foreignKey: LogicalTable['foreignKeys'][number],
  referencedTable: LogicalTable,
): string | undefined {
  const firstLocalColumnId = foreignKey.columnIds[0];
  const firstReferencedColumnId = foreignKey.referencedColumnIds[0];
  if (!firstLocalColumnId || !firstReferencedColumnId) return undefined;
  const localColumn = table.columns.find((c) => c.id === firstLocalColumnId);
  const referencedColumn = referencedTable.columns.find((c) => c.id === firstReferencedColumnId);
  if (!localColumn || !referencedColumn) return undefined;
  const suffix = `_${referencedColumn.name}`;
  if (!localColumn.name.endsWith(suffix)) return undefined;
  const qualifier = localColumn.name.slice(0, -suffix.length);
  return qualifier.length > 0 ? `fk_${table.name}_${qualifier}` : undefined;
}

function renderCreateTable(
  table: LogicalTable,
  tableById: ReadonlyMap<string, LogicalTable>,
  names: TableConstraintNames,
  options: SqlGenerationOptions,
): string {
  const K = (word: string) => applyKeywordCase(word, options.keywordCase);
  const primaryKeySet = new Set(table.primaryKey);
  const bodyLines: string[] = [];

  for (const column of table.columns) {
    const notNull = primaryKeySet.has(column.id) || !column.nullable;
    bodyLines.push(
      `  ${quotePostgreSqlIdentifier(column.name)} ${mapPostgreSqlDataType(column.dataType)}${notNull ? ` ${K('NOT NULL')}` : ''}`,
    );
  }

  if (table.primaryKey.length > 0 && names.primaryKey) {
    const columns = table.primaryKey.map((id) => quotePostgreSqlIdentifier(columnName(table, id)));
    bodyLines.push(
      `  ${K('CONSTRAINT')} ${quotePostgreSqlIdentifier(names.primaryKey)} ${K('PRIMARY KEY')} (${columns.join(', ')})`,
    );
  }

  for (const uniqueConstraint of table.uniqueConstraints) {
    const name = names.uniqueConstraints.get(uniqueConstraint.id);
    if (!name) continue;
    const columns = uniqueConstraint.columnIds.map((id) =>
      quotePostgreSqlIdentifier(columnName(table, id)),
    );
    bodyLines.push(
      `  ${K('CONSTRAINT')} ${quotePostgreSqlIdentifier(name)} ${K('UNIQUE')} (${columns.join(', ')})`,
    );
  }

  if (options.foreignKeyMode === 'inline') {
    for (const foreignKey of table.foreignKeys) {
      const name = names.foreignKeys.get(foreignKey.id);
      const referencedTable = tableById.get(foreignKey.referencedTableId);
      if (!name || !referencedTable) continue; // écarté par la validation défensive sinon
      bodyLines.push(
        `  ${renderInlineForeignKeyClause(table, foreignKey, referencedTable, name, options)}`,
      );
    }
  }

  return `${K('CREATE TABLE')} ${quotePostgreSqlIdentifier(table.name)} (\n${bodyLines.join(',\n')}\n)${terminator(options)}`;
}

function renderInlineForeignKeyClause(
  table: LogicalTable,
  foreignKey: LogicalTable['foreignKeys'][number],
  referencedTable: LogicalTable,
  constraintName: string,
  options: SqlGenerationOptions,
): string {
  const K = (word: string) => applyKeywordCase(word, options.keywordCase);
  const localColumns = foreignKey.columnIds.map((id) =>
    quotePostgreSqlIdentifier(columnName(table, id)),
  );
  const referencedColumns = foreignKey.referencedColumnIds.map((id) =>
    quotePostgreSqlIdentifier(columnName(referencedTable, id)),
  );
  return `${K('CONSTRAINT')} ${quotePostgreSqlIdentifier(constraintName)} ${K('FOREIGN KEY')} (${localColumns.join(', ')}) ${K('REFERENCES')} ${quotePostgreSqlIdentifier(referencedTable.name)} (${referencedColumns.join(', ')})`;
}

function renderAlterTableForeignKey(
  table: LogicalTable,
  foreignKey: LogicalTable['foreignKeys'][number],
  referencedTable: LogicalTable,
  constraintName: string,
  options: SqlGenerationOptions,
): string {
  const K = (word: string) => applyKeywordCase(word, options.keywordCase);
  const localColumns = foreignKey.columnIds.map((id) =>
    quotePostgreSqlIdentifier(columnName(table, id)),
  );
  const referencedColumns = foreignKey.referencedColumnIds.map((id) =>
    quotePostgreSqlIdentifier(columnName(referencedTable, id)),
  );
  return [
    `${K('ALTER TABLE')} ${quotePostgreSqlIdentifier(table.name)}`,
    `  ${K('ADD CONSTRAINT')} ${quotePostgreSqlIdentifier(constraintName)}`,
    `  ${K('FOREIGN KEY')} (${localColumns.join(', ')})`,
    `  ${K('REFERENCES')} ${quotePostgreSqlIdentifier(referencedTable.name)} (${referencedColumns.join(', ')})${terminator(options)}`,
  ].join('\n');
}

function escapeSqlStringLiteral(value: string): string {
  return value.replace(/'/g, "''");
}

function renderComments(table: LogicalTable, options: SqlGenerationOptions): string | undefined {
  const K = (word: string) => applyKeywordCase(word, options.keywordCase);
  const lines: string[] = [];
  if (table.description?.trim()) {
    lines.push(
      `${K('COMMENT ON TABLE')} ${quotePostgreSqlIdentifier(table.name)} ${K('IS')} '${escapeSqlStringLiteral(table.description)}'${terminator(options)}`,
    );
  }
  for (const column of table.columns) {
    if (!column.description?.trim()) continue;
    lines.push(
      `${K('COMMENT ON COLUMN')} ${quotePostgreSqlIdentifier(table.name)}.${quotePostgreSqlIdentifier(column.name)} ${K('IS')} '${escapeSqlStringLiteral(column.description)}'${terminator(options)}`,
    );
  }
  return lines.length > 0 ? lines.join('\n') : undefined;
}
