/**
 * Générateur de script PostgreSQL.
 *
 * Fine couche au-dessus du moteur partagé (`src/core/sql/shared/generate-script.ts`) :
 * ne décrit que ce qui est propre à PostgreSQL (échappement, types, limite de
 * 63 octets, `ALTER TABLE` par défaut avec `inline` disponible, `DROP TABLE
 * ... CASCADE`, commentaires via `COMMENT ON`). L'API publique
 * (`generatePostgreSqlScript`, `SQL_GENERATION_CODES`) est inchangée par
 * rapport à la v0.3.1 : aucune régression de comportement ni de nommage.
 */
import type { LogicalTable } from '../../logical-model/types';
import type { SqlGenerationOptions, SqlGenerationResult } from '../dialect';
import { DEFAULT_SQL_GENERATION_OPTIONS } from '../dialect';
import type { DialectSyntax } from '../shared/generate-script';
import { generateSqlScript, SQL_GENERATION_CODES } from '../shared/generate-script';
import { escapeSqlStringLiteral } from '../shared/string-literal';
import { mapPostgreSqlDataType } from './data-types';
import { quotePostgreSqlIdentifier } from './identifier';

export { SQL_GENERATION_CODES };

const POSTGRESQL_SYNTAX: DialectSyntax = {
  id: 'postgresql',
  header: '-- Generated by Modrise\n-- PostgreSQL dialect',
  quoteIdentifier: quotePostgreSqlIdentifier,
  mapDataType: mapPostgreSqlDataType,
  maxConstraintNameBytes: 63,
  allowedForeignKeyModes: ['alter-table', 'inline'],
  dropStatementSuffix: ' CASCADE',
  renderComments(table: LogicalTable, options, quote, K) {
    const lines: string[] = [];
    if (table.description?.trim()) {
      lines.push(
        `${K('COMMENT ON TABLE')} ${quote(table.name)} ${K('IS')} '${escapeSqlStringLiteral(table.description)}'${options.statementTerminator ? ';' : ''}`,
      );
    }
    for (const column of table.columns) {
      if (!column.description?.trim()) continue;
      lines.push(
        `${K('COMMENT ON COLUMN')} ${quote(table.name)}.${quote(column.name)} ${K('IS')} '${escapeSqlStringLiteral(column.description)}'${options.statementTerminator ? ';' : ''}`,
      );
    }
    return lines.length > 0 ? lines.join('\n') : undefined;
  },
};

export function generatePostgreSqlScript(
  model: Parameters<typeof generateSqlScript>[0],
  options: SqlGenerationOptions = DEFAULT_SQL_GENERATION_OPTIONS,
): SqlGenerationResult {
  return generateSqlScript(model, options, POSTGRESQL_SYNTAX);
}
